### ISSUE TITLE
Could you add Kubernetes HA 

### ISSUE THREAD

**Issue by coolpalani** [42devops/salt-kube#4]
Current setup is designed as single master, could you add Kubernetes HA where vagrant will spin up 3 masters and install all components.
Loadbalancer you can use Nginx in separate VM for balancing Kube APIs request

**Comment by iasonliu** [comment]
it supports kubernetes HA with multiple masters, but require Load balance on Cloud,  just setting `kube-master` as `grains` on your master VMs and update `pillar` as your `load balance IP`.

``` yaml
kubernetes:
  lookup:
    kube-apiserver:
      PUBLIC_ADDRESS: '172.16.10.10'
```

pls feel free to comment, if any question. thanks
